%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gfraga\Downloads\stimulus_words_german_copy.xlsx
%    Worksheet: multipic-DE
%
% Auto-generated by MATLAB on 20-Jun-2022 11:21:04

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "multipic-DE";
opts.DataRange = "C1:C751";

% Specify column names and types
opts.VariableNames = "NAME1";
opts.VariableTypes = "string";

% Specify variable properties
opts = setvaropts(opts, "NAME1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "NAME1", "EmptyFieldRule", "auto");

% Import the data
stimuluswordsgermancopy = readtable("C:\Users\gfraga\Downloads\stimulus_words_german.xlsx", opts, "UseExcel", false);



%% Clear temporary variables
clear opts

%% Check spelling 

words = table2array(stimuluswordsgermancopy)
words(1) = []; % remove first line (header) 
%doc2check = tokenizedDocument(words)
fixed = correctSpelling(words,'language','de')
%fixed= joinWords(fixed)
