---
title: "SINON Stimuli selection"
author: "G.Fraga Gonzalez"
date: "`r Sys.Date()`"
abstract: "We use German words from MULTIPIC database (picture matching task), using their entries in SUBTLEX (orthographic frequency info) and CLEARPOND (phonological info) databases. Then we used WUGGY to create matching pseudowords." 
runhead: "Stimuli selection"
output: 
  html_document:
      code_folding: hide
      toc: true
      toc_depth: 5
      toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gridExtra)
library(dplyr)
library(plotly)
library(ggplot2)
library(nomnoml)
library(kableExtra)
```


## Overview {.tabset}

### Initial selection

```{nomnoml flowchart, echo = FALSE, out.height=200}
#fontSize: 6
#arrowSize: .5
#stroke: black
#.box: dashed center
#.comment: fill=lightyellow empty bold
#lineWidth: 1
#direction: right
#leading: 1.25
#lineWidth: .75
#padding: 8
#spacing: 40
#zoom: 2
  
  [<database>Multipic|with phonol. info available|with pseudoword matches] n=565--> [Reject outliers| 1.lgSUBTLEX|2.PTAN|3.Ned1_Diff]
  [Reject outliers ] n=325-->[<comment> Sets of n = 65 |Set1 | Set2| Set3| Set4| Set4] 
  [<comment> Sets of n = 65 |Set1 | Set2| Set3| Set4| Set4]-- [<usecase>pseudorandomization*] 
    [<usecase>pseudorandomization*]-:> [Experiment Blocks]
  

```

```{r subsetting, echo=FALSE}
# Read data
rm(list=ls())

if( .Platform$OS.type == "windows" ){ dirinput <- 'V:/gfraga/'
} else if ( .Platform$OS.type == "unix"){ dirinput <- '/run/user/891957923/gvfs/smb-share:domain=d.uzh.ch,server=idnas12.d.uzh.ch,share=g_psyneulin_data$,user=gfraga/gfraga'
}
 
Merged <- openxlsx::read.xlsx(paste0(dirinput,'/Neuroling_SINON_stimuli.xlsx'),sheet = 'Merged')
# It's as simple as...
path <- "/media/55276F9D5951EC83/MyStatistics"


 
# Select only valid cases (e.g., Phono info available)
dat <- Merged[!is.na(Merged$PhoWord),]
  
# Outlier rejection:
  #lgSubtlex
  boxstats <- boxplot.stats(dat$lgSUBTLEX)
  dat <- dat[dat$lgSUBTLEX > boxstats$stats[1] & dat$lgSUBTLEX < boxstats$stats[5],]
  rm(boxstats)
  
  #PTAN (neighbor metric: phonological, neighbor metric: all, neighborhood frequency: all, value: size)
  boxstats <- boxplot.stats(dat$PTAN)
  dat <- dat[dat$PTAN > boxstats$stats[1] & dat$PTAN < boxstats$stats[5],]
  rm(boxstats)
  
  #ned1_diff (for associated Wuggy-pseudowords)
  boxstats <- boxplot.stats(dat$Ned1_Diff)
  dat <- dat[dat$Ned1_Diff > boxstats$stats[1] & dat$Ned1_Diff < boxstats$stats[5],]
 


# retrieve word 2 initial sounds 
dat$wordInitSounds <- paste0(sapply(strsplit(dat$PhoWord,".",fixed=TRUE),"[[",1),sapply(strsplit(dat$PhoWord,".",fixed=TRUE),"[[",2))


### Split in 'balanced' sets   
#-------------------------------------
## They must be balanced in :
## 1. lgSUBTLEX, PTAN and Ned1_Diff
## 2. Item length ??? 

## Add columns indicating a set number and a trial number within set
nTrialsInSet <- 65 
nSets <- 5 

if(nTrialsInSet*nSets !=nrow(dat)){ 
  stop('Stop! Reconsider how many sets you want to create')
}

dat$setIdx <- as.factor(rep(1:nSets, each = nTrialsInSet))
dat$setTrial <- as.factor(rep(1:nTrialsInSet,nSets))

# Compare the sets pairwise on several key variables.
# If finding significant differences in any of them: shuffle data,  reasign set and trials indices and compare again

vars2test <- c('lgSUBTLEX','PTAN','Ned1_Diff')
checkstats <- rep(0,length(vars2test))
cnt <- 0
while (sum(checkstats)!=length(checkstats)) {
  dat <- dat[order(sample(1:nrow(dat))),]
  dat$setIdx <- as.factor(rep(1:nSets, each = nTrialsInSet))
  dat$setTrial <- as.factor(rep(1:nTrialsInSet,nSets))
  print(dat[1:4,68:69])

  for (i in 1:length(vars2test)){
    attach(dat)
    #pairwise comparisons
    res.ts <- pairwise.t.test(get(vars2test[i]),setIdx, p.adj="none")
    
    # extract p values
    tps <- res.ts$p.value[which(!is.na(res.ts$p.value))]

    # Check if any was significant
    ifelse(test =length(which(tps<0.05))==0,
           yes = checkstats[i]<-1,
           no = checkstats[i]<-0)
  }

}
ttests <- list()
 for (i in 1:length(vars2test)){
    #pairwise comparisons
    res.ts <- pairwise.t.test(get(vars2test[i]),setIdx, p.adj="none")
    # store
    ttests[[i]] <- res.ts
 }

print(ttests)
sets <- split(dat,dat$setIdx)

### Shuffling 
#-------------------------------------
for (s in 1:length(sets)) {
    setdat <- sets[[s]]
    
    #Shuffle (the first two sounds must differ between consecutive items) 
    rowid <- 1:nrow(setdat)
    setdat <- setdat[order(sample(rowid)),]
    
    check <- matrix(NA,nrow(setdat))
    while (length(which(is.na(check)))>1) {
      setdat <- setdat[order(sample(rowid)),]
        for (i in 2:nrow(setdat)){
            ifelse(test = setdat$wordInitSounds[i]==setdat$wordInitSounds[i-1],check[i]<-NA,check[i]<- 0)
        } 
    }
    
    #add some info
    setdat$set <- s
    setdat$seqIdx <- 1:nrow(setdat)
    setdat <- relocate(setdat,'seqIdx')
    setdat <- relocate(setdat,'set')
    rownames(setdat) <- NULL
    
    # add to set list 
    sets[[s]] <- setdat
    rm(setdat)
    
}
  

```
## Data  {.tabset .tabset-pills .tabset-fade}

### Figures  {.tabset }

#### All selected items

Before outlier exclusion

```{r plots1, warning=FALSE,  verbose = FALSE,out.height=350,out.width=550}
 # quick plots
vars <- c('lgSUBTLEX','PTAN','Ned1_Diff')
fig<-list()
for (i in 1:length(vars)) {
  fig[[i]] <- plotly::ggplotly(
    ggplot(Merged,aes_string(y=vars[i])) + 
      geom_violin(aes(x=vars[i]),stat = 'ydensity',fill='dodgerblue',alpha=.2) +
      geom_boxplot(aes(x=vars[i]),width=.1,fill='dodgerblue') + 
      theme_bw()+theme(axis.title.x = element_blank())  
  )
  
  hoverinfo <- with(Merged, paste0("item: ", CORRECT_SPELL))
  fig[[i]]$x$data[[1]]$hoverinfo <- "none"
  fig[[i]]$x$data[[2]]$text <- hoverinfo
  fig[[i]]$x$data[[2]]$hoverinfo <- c("boxes")
}

plotly::subplot(fig[[1]],fig[[2]],fig[[3]]) %>% plotly::layout(title = paste0(dim(Merged)[1],' items'),font=11 )


```

After outlier exclusion

```{r plots2, warning = FALSE, verbose = FALSE,out.height=350,out.width=550}
 
# quick plots
vars <- c('lgSUBTLEX','PTAN','Ned1_Diff')
fig<-list()
for (i in 1:length(vars)) {
  fig[[i]] <- plotly::ggplotly(
    ggplot(dat,aes_string(y=vars[i])) + 
      geom_violin(aes(x=vars[i]),stat = 'ydensity',fill='green4',alpha=.2) +
      geom_boxplot(aes(x=vars[i]),width=.1,fill='green4',alpha=.7) + 
      theme_bw()+theme(axis.title.x = element_blank())  
  )
  
  hoverinfo <- with(dat, paste0("item: ", CORRECT_SPELL))
  fig[[i]]$x$data[[1]]$hoverinfo <- "none"
  fig[[i]]$x$data[[2]]$text <- hoverinfo
  fig[[i]]$x$data[[2]]$hoverinfo <- c("boxes")
}

plotly::subplot(fig[[1]],fig[[2]],fig[[3]]) %>% plotly::layout(title = paste0(dim(dat)[1],' items'),font=11 )


```

~*Hover\ mouse\ on\ data\ points\ for\ more\ info*~

#### Set 1 

```{r plots3, warning = FALSE, verbose = FALSE,out.height=350,out.width=750}

currDat <- data.table::rbindlist(sets)
 
# quick plots
vars <- c('lgSUBTLEX','PTAN','Ned1_Diff')
fig<-list()
for (i in 1:length(vars)) {
  fig[[i]] <- plotly::ggplotly(
    ggplot(currDat,aes_string(x='set',y=vars[i],group='set')) + 
    geom_violin(aes(x=set),stat = 'ydensity',fill='green4',alpha=.2) +
    geom_boxplot(aes(x=set),width=.1,fill='green4',alpha=.7) + 
    theme_bw()+theme(axis.title.x = element_blank(),title = element_text(vars[i]))
  )
  hoverinfo <- with(currDat, paste0("item: ", CORRECT_SPELL))
  fig[[i]]$x$data[[1]]$hoverinfo <- "none"
  fig[[i]]$x$data[[2]]$text <- hoverinfo
  fig[[i]]$x$data[[2]]$hoverinfo <- c("text","boxes")
}

plotly::subplot(fig[[1]],fig[[2]],fig[[3]],  margin = 0.05) %>% 
  plotly::layout(annotations=list(list(x = 0.1 , y = 1.1, text=vars[1],showarrow=F, xref='paper', yref='paper'),
                                  list(x = 0.5 , y = 1.1,text=vars[2],showarrow=F, xref='paper', yref='paper'),
                                  list(x = 0.9 , y = 1.1, text=vars[3],showarrow=F, xref='paper', yref='paper')))

#%>% plotly::layout(title = paste0(dim(currDat)[1],' items'),font=11 )


```

~*Hover\ mouse\ on\ data\ points\ for\ more\ info\ *~

### Tables  {.tabset}

#### set1 

```{r, verbose=FALSE, warning=FALSE}
sets[[1]] %>%
  kbl() %>%
  kable_paper("hover", full_width = F)

```

#### set2 

```{r, verbose=FALSE, warning=FALSE}
sets[[2]] %>%
  kbl() %>%
  kable_paper("hover", full_width = F)

```

#### set3 

```{r, verbose=FALSE, warning=FALSE}
sets[[3]] %>%
  kbl() %>%
  kable_paper("hover", full_width = F)

```

#### set4

```{r, verbose=FALSE, warning=FALSE}
sets[[4]] %>%
  kbl() %>%
  kable_paper("hover", full_width = F,)

```

#### set5

```{r, verbose=FALSE, warning=FALSE}
sets[[5]] %>%
  kbl() %>%
  kable_paper("hover", full_width = F)

```



