---
title: "Digits in Noise EEG" 
abstract: "The data current experiment is used in a submited manuscript by Thomas Houweling (under review). It is set to examine associations between EEG activity and speech in noise recognition. Task requires hearing a digit name embbeded in different levels of noise and pressing the corresponding digit in a pad (digits are 1:6,8:9). <br><br> Data from N = 25 adults (after 7 subjects discarded;initial sample mean age 23.5, SD=3.9 years; 29 female)  <br><br>  Performance measures per trial are accuracy (correct/incorrect) and clarity rating (1-9 subjective scale). SNR of presentation are calibrated per individual in a pretest,  defining 3 SNR levels: SRT50 (50% correctness in calibration test), SRT-1.5db (noisier), SRT+1.5db (less noisy). <br><br> Prestimulus alpha power (8.5-12Hz) in noisy trials was higher for correct than for incorrect trials, and for those rated as clearer vs less clear. Linear mixed effect logistic regression model: accuracy ~ α power * SNR + (1|subject:digit) using source-reconstructed power found significant prediction in a left posterior temporal area in -300  to -50 ms. Interaction with stimuli difficulty: positive influence of alpha for recognizing clearer targets, but negative influence for the less clear targets." 
runhead: "A Running Head"
author:
  name: Gorka Fraga Gonzalez  [Thomas Houweling dataset]
  affiliation: University of Zurich 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
      code_folding: hide
      highlight: espresso
      theme: spacelab
      toc: true
      toc_float:
          collapsed: false
          smooth_scroll: true
          toc_depth: 6
params:
    dirinput:  "W:/Transfer/forGorka"
        
      #self_contained: false
---


```{r, include=FALSE}
 
    knitr::opts_knit$set(root.dir = 'V:/gfraga/scripts_neulin/Projects/SINEEG')    
    knitr::opts_chunk$set(echo=TRUE,warning=FALSE)
    library(tidyr)
    library(dplyr)
    library(reactable)
    source('V:/gfraga/scripts_neulin/Projects/SINEEG/funs/eeg_funs.R')
    

    
```

```{r, include = FALSE}
options(width=60)
local({
  hook_output <- knitr::knit_hooks$get('output')
  knitr::knit_hooks$set(output = function(x,options) {
    if (!is.null(options$max.height)) options$attr.output <- c(
      options$attr.output,
      sprintf('style="max-height: %s;"',options$max.height)
    )
   hook_output(x, options)    
  })
})

```

### Folder tree {.tabset}
#### subfolders
```{r,max.height='600px'}
  
  # Print folder tree    
  fs::dir_tree(params$dirinput,recurse=TRUE,type='directory')

```
#### subfolders & files
```{r, max.height = '600px' }
  fs::dir_tree(params$dirinput,recurse=TRUE)
```

 