rm(list=ls())
library(dplyr)
library(tidyr)
###############################################################################
# SPREADSHEETS TO USE IN GORILLA
# ----------------------------------------------------------------------------
# - Read subsets of items generated by MATCH
# - Assign balanced SNR levels
# - Control pseudowords and their ref words are not in same block (LD task)
# - Export XLS file formmatted for Gorilla(indicating block etc)
###############################################################################

# directories 
dirinput <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v2/SINON_MATCH_subsets_50words'
dirinput100 <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v2/SINON_MATCH_subsets_100words'
databasedfile <-'V:/spinco_data/LIRI_database/LIRI_database_stimuli.xlsx'
diroutput <- 'V:/spinco_data/SINON/Spreadsheets'
setwd(dirinput)
#audiofiles
audiofiles_nvoc <- 'V:/spinco_data/Audio_recordings/LIRI_voice_DF/segments/items_OK_norm_vocoded/'
audiofiles_sissn <- 'V:/spinco_data/Audio_recordings/LIRI_voice_DF/segments/items_OK_norm_SiSSN/'
# 
filesnvoc <- dir(audiofiles_nvoc,pattern = '*.mp3')
filessissn <- dir(audiofiles_sissn,pattern = '*.mp3')

# search files and concat
database <- openxlsx::read.xlsx(databasedfile,sheet = 'Merged')
# SNR assignments to file suffices
snrLev <-   c('snr1','snr2','snr3','snr4','snr5')
snrs_voco <- c('4chans','5chans','6chans','7chans','8chans')
snrs_sissn <- c('10db','5db','0db','-5db','-10db')
 

# SPREADSHEETS  ###################################################################

# Lexical Decision ------------------------------------------
words <- list()
for (i in 1:5){
  currSet <-read.table(paste0('list2match_set',i,'.txt'))
  if (nrow(currSet) %% length(snrLev)!=0){
    stop("not possible to balance n trials per snr ! ")
  }
  #find matching pseudowords  # shuffle and add snr 
  wordsInSet <-database$CORRECT_SPELL[which(database$CORRECT_SPELL %in% currSet$V1)]
  wordsInSet <- wordsInSet %>% sample 
  snrInSet <- rep(snrLev,length(wordsInSet)/5)
  stimInSet <- rep('word',length(wordsInSet))
  words[[i]] <-as.data.frame(cbind(rep(paste0('block',i),length(wordsInSet)),
                                   wordsInSet,
                                   snrInSet,
                                   stimInSet))
}
words <- data.table::rbindlist(words)
colnames(words) <- c('block','item','snr','answer')
#
pseudo <- list()
for (i in 1:5){
  currSet <-read.table(paste0('list2match_set',i,'.txt'))
  if (nrow(currSet) %% length(snrLev)!=0){
    stop("not possible to balance n trials per snr ! ")
  }
  #find matching pseudowords  # shuffle and add snr 
  pseudoInSet <-database$Pseudoword[which(database$CORRECT_SPELL %in% currSet$V1)]
  pseudoInSet <- pseudoInSet %>% gsub('-','',.) %>% sample
  snrInSet <- rep(snrLev,length(pseudoInSet)/5)
  stimInSet <- rep('pseudo',length(pseudoInSet))
  pseudo[[i]] <-as.data.frame(cbind(rep(paste0('block',i),length(pseudoInSet)),
                                    pseudoInSet,
                                    snrInSet,
                                    stimInSet))
}
pseudo <- data.table::rbindlist(pseudo)
pseudo$V1 <- rev(pseudo$V1) # reverse block assignment of pseudowords so that words in each set do not appear together with the corresponding pseudo words from that set (avoid phonol bias)
colnames(pseudo) <- c('block','item','snr','answer')
 
# bring together, shuffle
ds <- rbind(words,pseudo)
ds <- ds[sample(1:nrow(ds)),] 
ds <- ds[order(block),]

# fill the file names based on multiple matching/replacements 
ds$file <- paste0(ds$snr,'.mp3')
ds$file <- ifelse(ds$block=='block1' | ds$block=='block3',
                 stringi::stri_replace_all_regex(ds$file,pattern = snrLev,replacement = paste0('norm_',snrs_voco),vectorize = FALSE),
                 stringi::stri_replace_all_regex(ds$file,pattern = snrLev,replacement = paste0('norm',snrs_sissn),vectorize = FALSE))

ds$file <- ifelse(ds$block=='block1' | ds$block=='block3',
                paste('NV',ds$item,ds$file,sep='_'),
                paste('SiSSN',ds$item,ds$file,sep='_'))

ds$noise <- ifelse(ds$block=='block1' | ds$block=='block3','NVoc','SiSSN') 
print(ds)

# fixsome bugs in the name so in the spreadsheet corresponds to actual files:
ds$file <- gsub('äsleyre_','äsleyre.2_', ds$file)
ds$file <- gsub('Nacaer_','Nacaer.2_',ds$file)
ds$file <- gsub('Lelfer_','Lelfer.1_',ds$file)

ds <- ds[which(ds$block!='block5'),]
# save in output dir 
dirout <-  paste0(diroutput,'/LexicalDecision/')
outputname <- paste0(dirout,'TrialSequences_LD.xlsx')
openxlsx::write.xlsx(ds,outputname)


 
# ###############
# # Picture matching task ----------------------------------------------------------
# setwd(dirinput100)
# rm(ds)
# ds <- list()
# for (i in 1:4){
#   currSet <-read.table(paste0('list2match100_set',i,'.txt'))
#   
#   if (nrow(currSet) %% length(snrLev)!=0){
#     stop("not possible to balance n trials per snr ! ")
#   }
#   # first add all pictures 
#   picture <- database$PICTURE[which(database$CORRECT_SPELL %in% currSet$V1 )]
#   name <- database$CORRECT_SPELL[which(database$CORRECT_SPELL %in% currSet$V1 )]
#   # Add whether they are match or not (50% match)
#   match <- c(rep(1,nrow(currSet)/2),rep(0,nrow(currSet)/2)) %>% sample()
#   
#   #Combine 
#   spreadsheet  <- as.data.frame(cbind(rep(paste0('block',i),nrow(currSet)), 
#                                       name,
#                                       rep(snrLev,nrow(currSet)/length(snrLev)),
#                                       picture,
#                                       match))
#                
#   # shuffle the pictures for the trials marked as not a match
#   original  <- spreadsheet$picture[which(spreadsheet$match==0)]
#   replacement <- sample(original)
#     while (length(which(original==replacement)>0)!=0) {# shuffle again until no name repeats position 
#     replacement <- sample(original)
#   } 
#   
#   spreadsheet <- spreadsheet[sample(nrow(spreadsheet)),]
#   # Add to list 
#   ds[[i]] <- spreadsheet
# }
# # Gather
# ds <- data.table::rbindlist(ds)
# colnames(ds) <- c('block','item','snr','pic','match') 
#  
# # fill the file names based on multiple matching/replacements 
# ds$file <- paste0(ds$snr,'.mp3')
# ds$file <- ifelse(ds$block=='block1' | ds$block=='block3',
#                   stringi::stri_replace_all_regex(ds$file,pattern = snrLev,replacement = paste0('norm_',snrs_voco),vectorize = FALSE),
#                   stringi::stri_replace_all_regex(ds$file,pattern = snrLev,replacement = paste0('norm',snrs_sissn),vectorize = FALSE))
# 
# ds$file <- ifelse(ds$block=='block1' | ds$block=='block3',
#                   paste('NV',ds$item,ds$file,sep='_'),
#                   paste('SiSSN',ds$item,ds$file,sep='_'))
# 
# ds$type <- ifelse(ds$block=='block1' | ds$block=='block3','NV','SiSSN') 
# 
#  
# # save in output dir 
# dirout <-  paste0(diroutput,'/PictureMatching/')
# outputname <- paste0(dirout,'TrialSequences_PIC.xlsx')
#  
# # save in output dir 
# openxlsx::write.xlsx(ds,outputname) 
# if (!dir.exists(paste0(dirout,'/files'))){
#   dir.create(paste0(dirout,'/files'))
#   file.copy(paste0(audiofiles_sissn,filessissn[which(filessissn %in% ds$file)]),paste0(dirout,'/files')) 
#   file.copy(paste0(audiofiles_nvoc,filesnvoc[which(filesnvoc %in% ds$file)]),paste0(dirout,'/files'))  
# }
# rm(ds)
