rm(list=ls())
library(dplyr)
library(tidyr)
###############################################################################
# SPREADSHEETS TO USE IN GORILLA
# ----------------------------------------------------------------------------
# - Read subsets of items generated by MATCH
# - Assign balanced SNR levels
# - Control pseudowords and their ref words are not in same block (LD task)
# - Export XLS file formmatted for Gorilla(indicating block etc)
###############################################################################

# directories 
dirinput <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v2/SINON_MATCH_subsets_50words'
dirinput100 <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v2/SINON_MATCH_subsets_100words'
databasedfile <-'V:/spinco_data/LIRI_database/LIRI_database_stimuli.xlsx'
diroutput <- 'V:/spinco_data/SINON/Spreadsheets'
setwd(dirinput)


# search files and concat
database <- openxlsx::read.xlsx(databasedfile,sheet = 'Merged')
# SNR assignments to file suffices
snrLev <-   c('snr1','snr2','snr3','snr4','snr5')
snrs_voco <- c('4chans','5chans','6chans','7chans','8chans')
snrs_sissn <- c('10db','5db','0db','-5db','-10db')


# SPREADSHEETS  ###################################################################

###############
# Picture matching task ----------------------------------------------------------
setwd(dirinput100)
rm(ds)
ds <- list()
for (i in 1:4){
  currSet <-read.table(paste0('list2match100_set',i,'.txt'))
  
  if (nrow(currSet) %% length(snrLev)!=0){
    stop("not possible to balance n trials per snr ! ")
  }
  # first add all pictures 
  picture <- database$PICTURE[which(database$CORRECT_SPELL %in% currSet$V1 )]
  name <- database$CORRECT_SPELL[which(database$CORRECT_SPELL %in% currSet$V1 )]
  # Add whether they are match or not (50% match)
  match <- c(rep(1,nrow(currSet)/2),rep(0,nrow(currSet)/2)) %>% sample()
  
  #Combine 
  spreadsheet  <- as.data.frame(cbind(rep(paste0('block',i),nrow(currSet)), 
                                      name,
                                      rep(snrLev,nrow(currSet)/length(snrLev)),
                                      picture,
                                      match))
  
  # shuffle the pictures for the trials marked as not a match
  original  <- spreadsheet$picture[which(spreadsheet$match==0)]
  replacement <- sample(original)
  while (length(which(original==replacement)>0)!=0) {# shuffle again until no name repeats position 
    replacement <- sample(original)
  } 
  
  spreadsheet <- spreadsheet[sample(nrow(spreadsheet)),]
  # Add to list 
  ds[[i]] <- spreadsheet
}
# Gather
ds <- data.table::rbindlist(ds)
colnames(ds) <- c('block','item','snr','pic','match') 

# fill the file names based on multiple matching/replacements 
ds$file <- paste0(ds$snr,'.wav')
ds$file <- ifelse(ds$block=='block1' | ds$block=='block3',
                  stringi::stri_replace_all_regex(ds$file,pattern = snrLev,replacement = paste0('norm_',snrs_voco),vectorize = FALSE),
                  stringi::stri_replace_all_regex(ds$file,pattern = snrLev,replacement = paste0('norm',snrs_sissn),vectorize = FALSE))

ds$file <- ifelse(ds$block=='block1' | ds$block=='block3',
                  paste('NV',ds$item,ds$file,sep='_'),
                  paste('SiSSN',ds$item,ds$file,sep='_'))

ds$type <- ifelse(ds$block=='block1' | ds$block=='block3','NV','SiSSN') 


# save in output dir 
dirout <-  paste0(diroutput,'/PictureMatching/')
outputname <- paste0(dirout,'TrialSequences_PIC.xlsx')

 