rm(list=ls())
library(dplyr)
library(tidyr)
###############################################################################
# SPREADSHEETS TO USE IN GORILLA
# ----------------------------------------------------------------------------
# - Read subsets of items generated by MATCH
# - Assign balanced SNR levels
# - Control pseudowords and their ref words are not in same block (LD task)
# - Export XLS file formmatted for Gorilla(indicating block etc)
###############################################################################

# directories 
dirinput <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v2/SINON_MATCH_subsets_50words'
dirinput100 <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v2/SINON_MATCH_subsets_100words'
databasedfile <-'V:/spinco_data/LIRI_database/LIRI_database_stimuli.xlsx'
diroutput <- 'V:/spinco_data/SINON/Spreadsheets'
setwd(dirinput)

# search files and concat
database <- openxlsx::read.xlsx(databasedfile,sheet = 'Merged')
# SNR assignments to file suffices
snrLev <-   c('snr1','snr2','snr3','snr4','snr5')
snrs_voco <- c('4chans','5chans','6chans','7chans','8chans')
snrs_sissn <- c('10db','5db','0db','-5db','-10db')
 

# SPREADSHEETS  ###################################################################

# Lexical Decision ------------------------------------------
words <- list()
for (i in 1:5){
  currSet <-read.table(paste0('list2match_set',i,'.txt'))
  if (nrow(currSet) %% length(snrLev)!=0){
    stop("not possible to balance n trials per snr ! ")
  }
  #find matching pseudowords  # shuffle and add snr 
  wordsInSet <-database$CORRECT_SPELL[which(database$CORRECT_SPELL %in% currSet$V1)]
  wordsInSet <- wordsInSet %>% sample 
  snrInSet <- rep(snrLev,length(wordsInSet)/5)
  stimInSet <- rep('word',length(wordsInSet))
  words[[i]] <-as.data.frame(cbind(rep(paste0('block',i),length(wordsInSet)),
                                   wordsInSet,
                                   snrInSet,
                                   stimInSet))
}
words <- data.table::rbindlist(words)
colnames(words) <- c('block','item','snr','answer')
#
pseudo <- list()
for (i in 1:5){
  currSet <-read.table(paste0('list2match_set',i,'.txt'))
  if (nrow(currSet) %% length(snrLev)!=0){
    stop("not possible to balance n trials per snr ! ")
  }
  #find matching pseudowords  # shuffle and add snr 
  pseudoInSet <-database$Pseudoword[which(database$CORRECT_SPELL %in% currSet$V1)]
  pseudoInSet <- pseudoInSet %>% gsub('-','',.) %>% sample
  snrInSet <- rep(snrLev,length(pseudoInSet)/5)
  stimInSet <- rep('pseudo',length(pseudoInSet))
  pseudo[[i]] <-as.data.frame(cbind(rep(paste0('block',i),length(pseudoInSet)),
                                    pseudoInSet,
                                    snrInSet,
                                    stimInSet))
}
pseudo <- data.table::rbindlist(pseudo)
pseudo$V1 <- rev(pseudo$V1) # reverse block assignment of pseudowords so that words in each set do not appear together with the corresponding pseudo words from that set (avoid phonol bias)
colnames(pseudo) <- c('block','item','snr','answer')
 
# bring together, shuffle
ds <- rbind(words,pseudo)
ds <- ds[sample(1:nrow(ds)),] 
ds <- ds[order(block),]

# fill the file names based on multiple matching/replacements 
ds$file <- paste0(ds$snr,'.mp3')
ds$file <- ifelse(ds$block=='block1' | ds$block=='block3',
                 stringi::stri_replace_all_regex(ds$file,pattern = snrLev,replacement = paste0('norm_',snrs_voco),vectorize = FALSE),
                 stringi::stri_replace_all_regex(ds$file,pattern = snrLev,replacement = paste0('norm',snrs_sissn),vectorize = FALSE))

ds$file <- ifelse(ds$block=='block1' | ds$block=='block3',
                paste('NV',ds$item,ds$file,sep='_'),
                paste('SiSSN',ds$item,ds$file,sep='_'))

ds$noise <- ifelse(ds$block=='block1' | ds$block=='block3','NVoc','SiSSN') 
print(ds)

# fixsome bugs in the name so in the spreadsheet corresponds to actual files:
ds$file <- gsub('C$sleyre_','C$sleyre.2_', ds$file)
ds$file <- gsub('Nacaer_','Nacaer.2_',ds$file)
ds$file <- gsub('Lelfer_','Lelfer.1_',ds$file)

ds <- ds[which(ds$block!='block5'),]
# save in output dir 
dirout <-  paste0(diroutput,'/LexicalDecision/')
outputname <- paste0(dirout,'TrialSequences_LD.xlsx')
openxlsx::write.xlsx(ds,outputname)

 